#!/bin/bash

if [ -f /usr/bin/google_speech-multilanguage ]; then
    mv /usr/bin/google_speech-multilanguage /usr/local/bin/google_speech-multilanguage
fi

update-alternatives --install /etc/alternatives/tts.gz tts "/usr/local/bin/google_speech-multilanguage" 20
update-alternatives --install /etc/alternatives/tts.gz tts "/usr/bin/espeak-ng-multilanguage" 15
update-alternatives --install /etc/alternatives/tts.gz tts "/usr/bin/pico2wave-multilanguage" 10
update-alternatives --remove tts /usr/bin/espeak 
update-alternatives --remove tts /usr/bin/espeak_fr
update-alternatives --remove tts /usr/local/bin/google_speech
update-alternatives --remove tts /usr/local/bin/google_speech_fr

if [ -f /usr/bin/pip3 ]; then
    /usr/bin/pip3 install google_speech
else
    /usr/local/bin/pip3 install google_speech
fi
