#!/bin/bash

# Auteur : benoitfra, paulluxwaffle
# Contact : 
# Version : 1.0
# Licence : GPL v3
# Fonction : Diction de l'heure 
# Shell : bash
# Paramètres : aucun
# Dépendance : espeak, mbrola, notify-send, google_speech

##### configuration du format de sortie de la date ("man date" pour plus d'option)  ########
HEURE=`date '+%H'`
MINUTE=`date '+%M'`

if [ $HEURE -gt 1 ]
then
    nombresDheure="heures"
else
    nombresDheure="heure"
fi

if [ $MINUTE -gt 1 ]
then
    nombresDeMinute="minutes"
else
    nombresDeMinute="minute"
fi

heure0=${HEURE:0:1}
heure1=${HEURE:1:1}

if [ $heure0 = 0 ]
then
    HEURE=$heure1
    if [ $heure1 = 0 ]
    then
        HEURE="minuit"
        nombresDheure=""
    elif [ $heure1 = 1 ]
    then
        HEURE="une"
    fi
elif [ $heure0 = 2 ] && [ $heure1 = 1 ]
then
    HEURE="vingt-et-une"
elif [ $heure0 = 1 ] && [ $heure1 = 2 ]
then
    HEURE="midi"
    nombresDheure=""
fi

minute0=${MINUTE:0:1}
minute1=${MINUTE:1:1}

if [ $minute0 = 0 ]
then
    MINUTE=$minute1
    if [ $minute1 = 1 ]
    then
        MINUTE="une"
    fi
elif [ $minute0 = 2 ] && [ $minute1 = 1 ]
then
    MINUTE="vingt-et-une"
elif [ $minute0 = 3 ] && [ $minute1 = 1 ]
then
    MINUTE="trente-et-une"
elif [ $minute0 = 4 ] && [ $minute1 = 1 ]
then
    MINUTE="quarante-et-une"
elif [ $minute0 = 5 ] && [ $minute1 = 1 ]
then
    MINUTE="cinquante-et-une"
fi


##### choix du type de voix à utiliser #####
VOIX=/opt/mbrola/fr4/fr4 
TYPE=mb/mb-fr4 
#VOIX=/opt/mbrola/fr1/fr1 (décommenter pour une voix d'homme)
#TYPE=mb/mb-fr1 


##### test pour savoir si la lecture est en route #####
if [ ! -z $(ps -A | grep mbrola | awk '{ print $1 }' ) ]; then
     kill $(ps -A | grep mbrola | awk '{ print $1 }' ) && sleep 2
fi

##### Notification de l'heure #####
/etc/alternatives/tts "il est $HEURE $nombresDheure et $MINUTE $nombresDeMinute" 
#notify-send -i "/usr/share/icons/HighContrast/scalable/actions-extra/history-view.svg" "`date`"
