#!/bin/bash

fc-cache -f -v

Texte1='    readonly property int itemSize\: units\.roundToIconSize\(Math\.\min\(Math\.min\(width, height\), units\.iconSizes\.enormous\)\)'
Texte2='    property int hiddenItemSize\: units\.iconSizes\.large'
file=/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml
sed -i "s/^.*property int itemSize.*/$Texte1/g" $file
sed -i "s/^.*property int hiddenItemSize.*/$Texte2/g" $file
cp /usr/share/icons/breeze/places/64/start.svg /usr/share/icons/breeze/places/64/start-here-kde.svg
cp /usr/share/icons/breeze-dark/places/64/start.svg /usr/share/icons/breeze-dark/places/64/start-here-kde.svg

FILE="/etc/default/grub"
LINE1='# Wallpapper Grub'
LINE2='GRUB_BACKGROUND="/usr/share/images/grub/grub_wallpaper.tga"'

grep -qF -- "$LINE1" "$FILE" || echo "$LINE1" >> "$FILE"
grep -qF -- "$LINE2" "$FILE" || echo "$LINE2" >> "$FILE"

FILE="/etc/skel/.config/kdeglobals"
Texte="LookAndFeelPackage=DVKBuntu-Light"
sed -i "s/^.*LookAndFeelPackage=.*/$Texte/g" $FILE

#update-grub

File=/etc/skel/.config/plasma-org.kde.plasma.desktop-appletsrc

if [ -f "$File" ]; then
    rm "$File"
fi

FILEOS='/etc/os-release'
sed -i 's/^NAME=.*/NAME=\"DVKBuntuLight"/g' "$FILEOS"
sed -i 's/^PRETTY_NAME=.*/PRETTY_NAME=\"DVKBuntuLight D1.0 alpha 20.04"/g' "$FILEOS"

FILELIBOS='/usr/lib/os-release'
sed -i 's/^NAME=.*/NAME=\"DVKBuntu"/g' "$FILELIBOS"
sed -i 's/^PRETTY_NAME=.*/PRETTY_NAME=\"DVKBuntuLight D1.0 alpha 20.04"/g' "$FILELIBOS"

FILELSB='/etc/lsb-release'
sed -i 's/^DISTRIB_ID=.*/DISTRIB_ID=DVKBuntu/g' "$FILELSB"
sed -i 's/^DISTRIB_DESCRIPTION=.*/DISTRIB_DESCRIPTION=\"DVKBuntuLight D1.0 alpha 20.04"/g' "$FILELSB"

FILEDESKTOPAuto1='/etc/skel/.config/autostart/dvkbuntu-easy-menu.desktop'
if [ ! -f $FILEDESKTOPAuto1 ]; then
    cp /usr/share/applications/dvkbuntu-easy-menu.desktop /etc/skel/.config/autostart/
fi

FILEDESKTOPAuto2='/etc/skel/.config/autostart/DVKBuntuMenuAccueil.desktop'
if [ -f "$FILEDESKTOPAuto2" ]; then
    rm "$FILEDESKTOPAuto2"
fi

FILE="/etc/skel/.config/DVKBuntuMenuAccueil.desktop"

if [ -f "$FILE" ]; then
    rm "$FILE"
fi

FILE="/etc/xdg/autostart/DVKBuntuMenuAccueil.desktop"

if [ -f "$FILE" ]; then
    rm "$FILE"
fi
