#! /bin/sh
# kcminputrc Mouse cursorTheme 'breeze_cursors'
kcminputrc_mouse_cursortheme=breeze_cursors
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=''
# ksplashrc KSplash Theme Breeze
ksplashrc_ksplash_theme=DVKBUNTU
# ksplashrc KSplash Engine KSplashQML
ksplashrc_ksplash_engine=KSplashQML
# kdeglobals KScreen ScaleFactor ''
kdeglobals_kscreen_scalefactor=1.8
# kdeglobals KScreen ScreenScaleFactors ''
kdeglobals_kscreen_screenscalefactors='DP-1-1=1.8;HDMI-1-1=1.8;HDMI-1-2=1.8;DP-1-2=1.8;DVI-D-1=1.8;HDMI-3=1.8;DP-3=1.8;'
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=173
