#!/bin/bash

# add space
mv '/opt/Easymenu' '/opt/Easy menu'

# Link to the binary
ln -sf '/opt/Easy menu/dvkbuntu-easy-menu' '/usr/bin/dvkbuntu-easy-menu'

# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/Easy menu/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
